name: code_mirrorer

# version: 1.0.0-commando

on:
  push:
    branches-ignore:
    - "main"
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "main"
    - "ga-ignore-*"

env:
  SOURCE: Asperboard/epickup
  MIRROR_URL: "EpitechPromo2027/G-EIP-600-PAR-6-1-eip-henry.letellier"
  GITHUB_SSH_KEY: ${{ secrets.MIRROR_SSH_SECRET }}

jobs:

  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    # - name: Push the content to the mirror repository
    #   uses: pixta-dev/repository-mirroring-action@v1
    #   with:
    #     target_repo_url: git@github.com:${{ env.MIRROR_URL }}.git
    #     ssh_private_key: ${{ env.GITHUB_SSH_KEY }}

